### ISSUE TITLE
发送群聊消息是需要跑命令来触发的吗？

### ISSUE THREAD

**Issue by lvwapro** [guMcrey/version-rocket#10]

**Comment by guMcrey** [comment]
是的
1. 创建 message-config.json, 具体字段请参考[文档](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#%E6%94%AF%E6%8C%81%E6%8E%A8%E9%80%81%E9%83%A8%E7%BD%B2%E6%88%90%E5%8A%9F%E7%9A%84%E9%80%9A%E7%9F%A5%E5%88%B0-%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1wecom-%E7%BE%A4%E8%81%8A)
2. 在 package.json 的 scripts 里创建一个自定义指令: 如 `send-message`
3. 控制台执行 `npm run send-message` 即可
```
"scripts": {
  "send-message": "send-wecom-message"
}
```

**Comment by lvwapro** [comment]
`// 1. Step one: import checkVersion(), and use
import { checkVersion } from 'version-rocket'
// By default, it is recommended to use the version field in package.json, and if there is a custom version, ignore this line
import { version } from '../package.json'

checkVersion({
  localPackageVersion: version,
  originVersionFileUrl: `${location.origin}/version.json`,
})`
这部分代码写在哪个文件里面呢？

**Comment by guMcrey** [comment]
一般写在项目入口文件里
如果你是 Vue 项目，写在 App.vue 里
如果你是 React 项目，写在 App.jsx 或 App.tsx 里
如果是其他项目，也类似

**Comment by lvwapro** [comment]
单页面应用，路由懒加载，manifest
如果更新后的版本在上一个页面加传了几个字段之类的，
而旧的版本更新后获取不到这几个字段，会不会报错。

**Comment by guMcrey** [comment]
> 单页面应用，路由懒加载，manifest 如果更新后的版本在上一个页面加传了几个字段之类的， 而旧的版本更新后获取不到这几个字段，会不会报错。

你好, 我不太理解这个问题描述的场景, 最好能提供下 demo 或者代码片段
