### ISSUE TITLE
'MESSAGE_PATH' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by ysneo** [guMcrey/version-rocket#12]
![image](https://user-images.githubusercontent.com/17615113/200247406-afc85d9d-f835-412d-9e25-7ec8bb6e2763.png)

v1.3.0

**Comment by ysneo** [comment]
![image](https://user-images.githubusercontent.com/17615113/200253201-a497d5d1-1e50-4fcb-9e52-7b52b016c63d.png)
这两个参数没有在卡片很好的展出；
![image](https://user-images.githubusercontent.com/17615113/200253314-dd285fb6-e4f4-4130-9c49-f958fd83e1a1.png)

**Comment by guMcrey** [comment]
你好呀, 感谢关注, 问题我仔细看了, 首先 **对于你提到的 “`deployToolsText` 和 `deployTools` 字段没有在卡片上展示“ 的问题**
- **解决方案:**
  - 1. 将 package.json 中 `"send-lark-message:test": "MESSAGE_PATH=./lark-message-config.json send-lark-message"` 改为 `"send-lark-message:test": "send-lark-message"`
  - 2. 确保根目录下的 `lark-message-config.json` 文件中设置了 `deployToolsText` 和 `deployTools` 字段且值不为空字符串
      ```
       ...
       "deployToolsText": "Deploy tools text",
       "deployTools": "Jenkins"
      ```
  - 3. 在目标项目中运行 yarn send-lark-message:test 验证是否与预期一致
  
如果以上步骤都尝试后仍然存在问题, 请留言, 并附上你的 ` lark-message-config.json ` 文件的配置信息 (建议将敏感信息删掉)

---

- **对于 **'MESSAGE_PATH' is not recognized as an internal or external command** 执行时的报错:**  
   - 原因: 大概率是由于 windows 系统对于环境变量的命名存在一点差异, 我今天晚一点会测试下, 然后给出解决示例
   - 如果你发送 lark 消息的文件名是 lark-message-config.json 的话, MESAGE_PATH 是不需要设置的, 去掉即可

---

- 其他问题

注意到你的第一张截图中, package.json 文件中配置的 `send-lark-message:test` 命令中 `MESSAGE_PATH` 所指向的文件是 `send-lark-message.json`, 但是在运行 `yarn send-lark-message:test` 时获取的文件却是 `lark-message-configa.json`, 文件名两处不一致, 这个可能需要你自己排查下问题

![image](https://user-images.githubusercontent.com/26329117/200270903-3391e5b5-692d-4f3e-aa83-b25e15b2e8bb.png)

**Comment by ysneo** [comment]
嗯 感谢回复；
关于这个deploy的信息我看效果是展示在和remark一起的，展示的小字，我的期望是展示到和上面的项目名称一样，大卡片
![image](https://user-images.githubusercontent.com/17615113/200279766-9ea0282d-099b-4544-aa0a-45827125ed98.png)
![image](https://user-images.githubusercontent.com/17615113/200280132-b47f6764-cbde-48f8-8ed2-34f459ba20e4.png)


不知道我的建议怎么样， 不然我只能 fork改源码了 😂

--- 

'MESSAGE_PATH' 还请麻烦看下，我需要不同环境不同配置文件。

**Comment by guMcrey** [comment]
1. 部署平台放大卡片可以的, 我今天会发布 `V 1.3.1` 加上
   - 考虑到大家还有别的希望自定义的字段放在主卡片上, 我之后会将这部分升级下, 支持动态可配置的, 敬请期待 😝  
2. `MESSAGE_PATH` 的问题, 我测试好, 今天晚些回复你

感谢💗

**Comment by guMcrey** [comment]
- V 1.3.1 已发布，在 lark-message-config.json 文件中新增如下配置用于设置部署信息展示位置：
  - setDeployInfoInMainCard 为 true 时，部署信息将会显示在卡片中（同项目名称）； 为 false 时， 默认展示在卡片底部 （同 remark）
  - deployToolsLabel 用于自定义设置部署信息标题
  - deployTools 为部署信息详情
 
    ```
    "setDeployInfoInMainCard": true,
    "deployToolsLabel": "部署平台"，
    "deployTools": "Make"
    ```

- MESSAGE_PATH' is not recognized as an internal or external command 执行时的报错的解决方案
  - 在你的项目中安装 cross-env
    ```
    npm install cross-env -D
    ```
  - 然后在 MESSAGE_PATH 之前加 cross-env
    ```
    "send-lark-message:test": "cross-env MESSAGE_PATH=./lark-message-config.json send-lark-message"
    ```
  - 执行 `npm run send-lark-message:test` 即可


因为在 windows 系统中设置环境变量的语法不同于 Linux 系统等， 需要借助 cross-env 包来配置， 感兴趣可以看一下它的官网， 我之后也会把这部分内容补充到 README.md 中， 感谢反馈

**Comment by ysneo** [comment]
好的 感谢升级; 我要试试新功能了

**Comment by ysneo** [comment]
有个bug， remark 没出来
![image](https://user-images.githubusercontent.com/17615113/200546549-feb9fd99-a37a-45ae-b75e-d062588fa94d.png)

**Comment by guMcrey** [comment]
真是抱歉, 测试用例没有覆盖全, V 1.3.2 已修复

感谢反馈❤️

**Comment by guMcrey** [comment]
V 1.3.2 已修复

真是抱歉, 测试用例没有覆盖全, 感谢反馈, 笔芯❤️

**Comment by CLiangs** [comment]
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/24502999/215666969-a31211e9-3931-497e-9a8f-c15435a87a66.png">根目录下有文件为啥提示没有呢

**Comment by ysneo** [comment]
> <img alt="image" width="1476" src="https://user-images.githubusercontent.com/24502999/215666969-a31211e9-3931-497e-9a8f-c15435a87a66.png">根目录下有文件为啥提示没有呢

cross-env 是不是忘加了

**Comment by CLiangs** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/24502999/215679780-4f32667f-78ad-4da7-8996-8705745e2e6f.png">
mac系统、 加了也不行。 感觉是我的系统哪里出问题了。。。

**Comment by ysneo** [comment]
> <img alt="image" width="1096" src="https://user-images.githubusercontent.com/24502999/215679780-4f32667f-78ad-4da7-8996-8705745e2e6f.png">
> 
> mac系统、 加了也不行。 感觉是我的系统哪里出问题了。。。

"cross-env": "^7.0.3",  这个包要装一下

**Comment by CLiangs** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/24502999/215681657-efa5bf3d-b670-418e-8431-e1bfad733d8b.png">
有安装 还是报一样的错误

**Comment by guMcrey** [comment]
#21 
@CLiangs 你好, 通过你提供的截图, 我查了一些资料, 可以给你两个解决方案, 你都尝试下, 看是否有效
- **方案1**
   - 更新下 VSCode 中的 **Prettier** 插件版本, 后重启 VSCode, 然后重新运行 `yarn send-wecom-message:test`
   > 依据来自这里 https://www.cnblogs.com/shanejix/p/15772813.html

- **方案2**
   - 用 npm 替换 yarn, 删除 node_modules, 使用 `npm install` 安装依赖后再重试

因为我这边没法复现出来, 尝试后麻烦反馈下结果, 谢谢

**Comment by CLiangs** [comment]
方案1试了不行。 方案2用npm替换yarn 有效，可以使用。但是不太喜欢用npm

**Comment by guMcrey** [comment]
正常情况使用 yarn 也不会出现这种问题, 我在 mac 中测试过, 没有复现 `node\r no such file or directory` 这个问题, 如图

<img width="300" src="https://user-images.githubusercontent.com/26329117/215929339-76c48c71-ba85-4eb2-bb21-349efc14141a.png" />

---

所以应该和你本地系统配置有关, 建议你从几方面来尝试解决这个问题, 着重点可以看下这个报错提示 `node\r no such file or directory`, 其中的 \r 是不太正常的, 大概率是系统解析出错, 导致命令无法正常执行
- 尝试重新安装 yarn 包
- 尝试重新安装 node
- 尝试重新安装 npm
> 具体可以参考这里: https://stackoverflow.com/questions/43465086/env-node-no-such-file-or-directory-in-mac

希望能帮到你 🐶

**Comment by qianyiliushang** [comment]
这个问题的根源是generate-version-file这个文件的回车换行用的是CRLF导致在Mac下执行失败，最好出个版本解决一下，我本来是来提这个issue的，发现这里在讨论这个问题
文件目录：node_modules/.bin/generate-version-file 
解决办法：编辑器里手动把CRLF改为LF即可
<img width="950" alt="image" src="https://user-images.githubusercontent.com/6229122/221812826-d2a82991-3b8f-46e2-a991-4ba29a7ca62c.png">

**Comment by guMcrey** [comment]
@qianyiliushang 你好呀, 这个问题我们在新的 issue 里来讨论吧 [#21](https://github.com/guMcrey/version-rocket/issues/21)

感谢反馈 💗
针对这个问题, 我给出了详细的原因分析和解决方案, 看这里 [#21](https://github.com/guMcrey/version-rocket/issues/21)
如果问题没有解决的话, 我们可以在这里 [#21](https://github.com/guMcrey/version-rocket/issues/21) 继续讨论~~
