### ISSUE TITLE
前端小白，请问checkVersion函数是要放在App.vue的哪里呀？

### ISSUE THREAD

**Issue by zzzlzp** [guMcrey/version-rocket#13]

**Comment by zzzlzp** [comment]
![1668601714805](https://user-images.githubusercontent.com/33389134/202181811-35980829-7884-4d13-9a9a-9a24d89acfb0.jpg)
![WX20221116-203036@2x](https://user-images.githubusercontent.com/33389134/202181844-698dcec2-76f4-4ec9-a44e-8e00c8ea7e01.png)
![1668601872312](https://user-images.githubusercontent.com/33389134/202181862-0ec83b35-5884-4cda-8455-f2bc242901fe.jpg)
![1668602002786](https://user-images.githubusercontent.com/33389134/202181883-d5818ba4-2efd-4316-af1f-9ecd18f461ee.jpg)

**Comment by zzzlzp** [comment]
![WX20221116-203652@2x](https://user-images.githubusercontent.com/33389134/202182640-fe2953a1-f5f4-410d-b183-45b219b15967.png)
![1668602239734](https://user-images.githubusercontent.com/33389134/202182650-807c0c9c-712c-4b09-9a60-2bfa4dc74641.jpg)
![WX20221116-203730@2x](https://user-images.githubusercontent.com/33389134/202182655-e7b0bbc1-bfe6-4fb9-a6b3-03e53bf7dc34.png)
这样操作是哪里有问题吗？不是很明白，求大佬指点

**Comment by guMcrey** [comment]
你好呀, 感谢关注

**使用方式如下:**

1. checkVersion 函数可以写在 App.vue 的生命周期中, 例如 mounted (Vue 2.x) 或 onMounted (Vue 3.x) 中
*以下以 Vue3.x 为例*
```vue
<script setup>
import { onMounted } from 'vue'
import { checkVersion } from 'version-rocket'
// 推荐使用 package.json 中的 version 字段, 也可自定义 version
import { version } from '../package.json'

onMounted(() => {
    checkVersion({
      localPackageVersion: version,
      originVersionFileUrl: `${location.origin}/version.json`,
    }, {
      // 自己的自定义配置
    })
})
</script>
```

2. package.json scripts 中设置执行命令
其中 VERSION 字段, 如果使用 package.json 中的 version 的话, 这个字段不需要设置, 去掉即可, 更多信息可以看下 [README.md](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md)
```
"generate:version": "generate-version-file dist public"
```

2. 当前项目控制台执行 (或在任何需要的地方设置, 一般需要在 ci/cd 时执行该命令)
```
npm run generate:version
```

4. 此时 public 和 dist 目录就生成了 version.json 文件, version 为 package.json 中的值
开发环境测试时: 如果想要让版本更新弹窗显示, 只需要修改 package.json 的 version 值或 public 目录下的 version.json 文件中的 version 即可, 简言之, 只要保证 package.json 的 version 和 public 下的 version.json 的 version 不同即可

原理或更多信息可以参考 [README.md](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md)

**Comment by zzzlzp** [comment]
非常感谢大佬的解答，我在基础vue工程很快就实现了。然后移植到项目后费了很大的力气，因为获取远端version.json的路径一直有一些问题，导致无法正确获取version.json中的值。现在已经解决了，然后我还有一个问题，这个插件只能检查两个版本之间的版本号是否一致吗？我点了refresh后，页面刷新了，但是package.json中的version和version.json中的version的值都不会改变，这个改变version值的逻辑需要我自己补充吗？

**Comment by zzzlzp** [comment]
最简单的做法是每次上线之前手动修改一下package.json和version.json中的version的值，是这样吗？

**Comment by guMcrey** [comment]
> 非常感谢大佬的解答，我在基础vue工程很快就实现了。然后移植到项目后费了很大的力气，因为获取远端version.json的路径一直有一些问题，导致无法正确获取version.json中的值。现在已经解决了，然后我还有一个问题，这个插件只能检查两个版本之间的版本号是否一致吗？我点了refresh后，页面刷新了，但是package.json中的version和version.json中的version的值都不会改变，这个改变version值的逻辑需要我自己补充吗？

**问题1: 这个插件只能检查两个版本之间的版本号是否一致吗？**
- 是的, 检测用户浏览器当前运行的项目版本和服务端部署的最新版本是否一致, 本质上是比较用户当前运行的 package.json 中的 version 与远程服务器中的 version.json 中的 version 是否一致. 不一致则提示用户刷新


**问题2: 我点了refresh后，页面刷新了，但是 package.json 中的 version 和 version.json 中的 version 的值都不会改变, 这个改变version 值的逻辑需要我自己补充吗？**
- 调用 checkVersion 方法后不需要再做多余的逻辑处理. 只需要在每次上线发版前, 只修改 package.json 中的 version 版本即可, 可以手动修改, 也可以使用 npm version 命令
```
// 1.0.0 为新版本号
npm version 1.0.0
```
- 点击 refresh 发生了什么呢? 比如用户当前浏览器运行版本是 1.0.0 (由于缓存或窗口打开很久未操作), 而我们最新发布的版本是 1.1.0,  想要用户使用最新 1.1.0 版本. 使用了 version-rocket 包的 checkVersion 方法后, 自动定时检测用户版本, 若需要更新, 展示更新弹窗, 用户点击 refresh 按钮后刷新页面, 加载最新版 1.1.0, 就达到了我们希望用户使用最新版应用的目的

更多的原理相关内容可以看下 [README.md](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md) 哦

**Comment by guMcrey** [comment]
> 最简单的做法是每次上线之前手动修改一下package.json和version.json中的version的值，是这样吗？

每次上线前修改 `package.json` 中的 `version` 值就可以了. 并保证部署静态资源到服务器之前执行了 `generate-version-file dist public` 指令

比如可以这样:

1. 更新版本号
```
// 其中 1.0.0 为新版本号
npm version 1.0.0
```

2. 修改 package.json 的 scripts build 命令
_将 build 与 generate-version-file 命令合并, 方便操作_
```
"build": "vite build && generate-version-file dist public"
```

3. 打包资源 (build 后最新版本 1.0.0 的 version.json 文件已经在 dist 和 public 目录下生成了)
```
npm run build
```

4. 正常部署即可

**Comment by zzzlzp** [comment]
感谢大佬解答困惑，目前可以正常使用了，功能很好用。
还有一个问题，显示更新的样式可以自己改吗，
<img width="191" alt="WeChatf48b3bea18b205facfc69ba8fdc71c93" src="https://user-images.githubusercontent.com/33389134/202416566-81f9998e-b829-4350-a231-c13af57f2c28.png">
目前是这样的，改成其他的，比如在右上角弹出一个下面这样的通知框
<img width="271" alt="WeChat081d9b2fec0f1665c4aec050aceb1c2b" src="https://user-images.githubusercontent.com/33389134/202417089-f4493c95-b6fb-467a-afd5-744491d77bab.png">

**Comment by guMcrey** [comment]
弹窗样式是支持自定义的
- 如果只是希望改改主题色或者提示图片的话, 可以看下 [个性化设置主题](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#%E4%B8%AA%E6%80%A7%E5%8C%96%E8%AE%BE%E7%BD%AE%E4%B8%BB%E9%A2%98) 的教程
- 如果 UI 改动较大的, `checkVersion` 方法支持传入 `onVersionUpdate` 回调函数, 可以自定义自己的弹窗 UI, 具体使用方法如下
```
checkVersion({
    localPackageVersion: version,
    originVersionFileUrl: `${location.origin}/version.json`,
    onVersionUpdate: (data) => {
      console.log(data)     // refreshPageVersion: "1.1.0"
    },
  }, {
    // 自己的自定义配置
  }
)
```
</br>

[API 列表](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#api)
onVersionUpdate | function(data) | 自定义版本提示 UI 的回调函数 (如果你想自定义弹窗 UI, 通过回调函数可以拿到返回值来控制弹窗的显隐 )
-- | -- | --

**Comment by zzzlzp** [comment]
好的，我了解了，非常感谢大佬解答困惑。
