### ISSUE TITLE
可否增加自定义提示位置，大小，并且增加遮罩层配置项？

### ISSUE THREAD

**Issue by edisonyan** [guMcrey/version-rocket#14]
某些更新可能需要强制更新，能否增加遮罩层配置选项

**Comment by guMcrey** [comment]
你好呀, 感谢关注

目前没有计划做这样的配置, 不过弹窗样式是支持自定义的
- 对于 UI 改动较大的或有定制需求的, `checkVersion` 方法支持传入 `onVersionUpdate` 回调函数, 可以自定义自己的弹窗 UI, 具体使用方法如下
```
checkVersion({
    localPackageVersion: version,
    originVersionFileUrl: `${location.origin}/version.json`,
    onVersionUpdate: (data) => {
      console.log(data)     // refreshPageVersion: "1.1.0"
    },
  }, {
    // 自己的自定义配置
  }
)
```
</br>

[API 列表](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#api)
onVersionUpdate | function(data) | 自定义版本提示 UI 的回调函数 (如果你想自定义弹窗 UI, 通过回调函数可以拿到返回值来控制弹窗的显隐 )
-- | -- | --
