### ISSUE TITLE
大佬，有两个问题想请教一下

### ISSUE THREAD

**Issue by zzzlzp** [guMcrey/version-rocket#15]
1. 我把checkVersion函数写在了mounted里，因为当前这个项目是一个子项目，类似于微前端这样子，嵌入到其他的工程中。第一次进入我这个项目会触发mounted，当离开我的这个项目，到另一个人的项目之后，checkVersion是持续在工作的，再次进入我的这个项目，会再次触发mounted，再次运行checkVersion，这样按道理来说会运行两个checkVersion，不过我在浏览器开发者模式中，只看到一个checkVersion在运行，这里是做了什么处理吗？

**Comment by zzzlzp** [comment]
2.还是上述所说的，我的项目是一个子项目，进入我这个项目会触发mounted，再进入另一个项目之后，checkVersion在持续工作，后续有没有考虑添加一个卸载函数，类似于vue的watch和unwatch这样，在不需要运行checkVersion的时候对其进行卸载。

**Comment by guMcrey** [comment]
- 请问使用了什么技术方案实现的微前端呢? 因为主流的微前端方案原理不尽相同. 对于 version-rocket, 如果重复调用 checkVersion 会运行多次的, 我只针对版本弹窗做单例处理, 简言之, 如果已有弹窗在展示, 则不再展示
- 可以提供一个卸载函数, 我会在 V1.4.0 提供这个函数, 请关注一下

感谢反馈 ♥️

**Comment by guMcrey** [comment]
@zzzlzp 你好呀, unCheckVersion 卸载函数已添加, 使用方法如下

1. 安装 version-rocket 1.4.0
```
npm install version-rocket@latest
```
2. 引入 unCheckVersion 方法, 在需要的时候调用 unCheckVersion

```
import { unCheckVersion } from 'version-rocket'

// vue3.x
import {onUnmounted} from 'vue'
onUnmounted(() => unCheckVersion({ closeDialog: false }))

// vue2.x
beforeDestroy() {
   unCheckVersion({ closeDialog: false })
}
```
---

[API](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#api)

**unCheckVersion 方法**
> 终止在调用 `checkVersion` 后创建的 `worker` 进程

| 参数 | 类型 | 描述 | 默认值 | 必需 |
| --- | --- | --- | --- | --- |
closeDialog | boolean | 是否关闭版本更新提示弹窗 | - | 是

**Comment by zzzlzp** [comment]
1. 具体什么技术这个我也不是很清楚，是公司内部人做的，我对前端基本就是一知半解的，不是专门做前端的。意思是如果多次触发mounted就会多次调用checkVersion是吧，可能是我没有测试到，我再测试一下看看，试试有没有什么好的解决办法。
2. 非常感谢大佬能够提供卸载函数！

**Comment by wuhao-max** [comment]
你好，作者，我也有同样的问题，我们的前端项目是一个vue工程，然后我的这个工程的页面是需要当成外链嵌入到别的网站中，举个例子吧：
我有页面A和页面B，都会被当成一个独立的页面iframe嵌入到别的系统中，那么我在app.vue的生命周期函数中checkVersion，这时候别的系统中现打开A页面，再打开B页面，都i会执行app.vue中的checkVersion，同理，如果有几十个页面被嵌入到别的系统中，是不是会执行几十次的checkVersion，这时候是不是会增加服务器的压力啊？请问有什么办法解决么？

**Comment by guMcrey** [comment]
@wuhao-max  你好呀, 这种应用场景中由于每个 `iframe`  都有独立的执行环境, 所以 `checkVersion()` 会被执行多次, 我这边有三个方案可以优化:
1. **在你项目的 App.vue 的卸载函数中调用 unCheckVersion 方法**, 如图 (可以参考下上面评论里的写法):
<img src="https://github.com/guMcrey/version-rocket/assets/26329117/f27d6ca4-2af0-4a25-90bf-585c6563cf89" width="500" />

2. **如果你们的主项目和子项目是自己团队维护的推荐这样做:** 
   把 `version-rocket` 接入到主项目来, 由主项目来统一管理版本, 子项目的 `version-rocket` 去掉
 
4. **如果你们的主项目和子项目是跨团队合作的, 不太方便**:
   我近期会更新一版来专门解决这种应用场景下的性能问题, 发版后同步你
  
---
谢谢你的反馈ᵔᴥᵔ
