### ISSUE TITLE
generate:version 命令错误

### ISSUE THREAD

**Issue by Niofh** [guMcrey/version-rocket#16]
"generate:version": "VERSION=1.1.0-beta generate-version-file dist public "

'VERSION' 不是内部或外部命令，也不是可运行的程序，这个是怎么处理

**Comment by guMcrey** [comment]
你好呀, 感谢关注

**'VERSION' 不是内部或外部命令，也不是可运行的程序. 解决方案**

- 在你的项目中安装 cross-env
  ```
  npm install cross-env -D
  ```
- 然后在 VERSION 之前加上 cross-env
  ```
  generate:version": "cross-env VERSION=1.1.0-beta generate-version-file dist public"
  ```
- 最后执行 `generate:version` 即可
  ```
  npm run generate:version
  ```

因为在 windows 系统中设置环境变量的语法不同于 Linux 系统等， 需要借助 cross-env 包来配置， 感兴趣可以看一下它的官网， 我之后也会把这部分内容补充到 README.md 中， 感谢反馈 💗
