### ISSUE TITLE
建议增加配置

### ISSUE THREAD

**Issue by NWUFLAME** [guMcrey/version-rocket#17]
1. 建议增加immediately: boolean配置，首次立刻触发一次检测，否则 例如设置了10分钟的轮询间隔，程序启动10分钟后才会触发检测
2. 建议增加取消按钮 cancelText  或 关闭的叉号， 现在只能选择更新，不能选择取消更新
3. 建议点击refresh button支持自定义事件，默认做页面reload不够灵活，可能还想做一些其他事情

**Comment by guMcrey** [comment]
你好呀, 感谢关注

都是很不错的建议, 我会尽快安排上, 到时候同步给你~~

感谢反馈 💗

**Comment by guMcrey** [comment]
久等啦，你建议的配置选项都加好了，安装 version-rocket@1.5.0 即可体验😜
以下是新增的配置项说明及使用方法

1. **新增 `immediate` 选项**：支持首页访问时, 立即触发版本监测, 之后按自定义的时间间隔轮询，如 10 分钟。 (以减少请求服务器次数)
  ```
  checkVersion({
    ...
    pollingTime: 600000,
    immediate: true,
  })
  ```

---

2. **支持取消更新**

    - **新增 `cancelButtonText` 选项**：设置 cancelButtonText 自定义取消更新的按钮文案，以开启取消更新
    - **新增 `cancelMode` 选项**：取消更新后, 下一次何时更新。支持三种模式：
       - **`ignore-current-version`**：表示忽略此版本，当下次有版本更新时再提示（**默认值**）
       - **`ignore-today`**：表示当天不再提示，第二天开始提示
       - **`ignore-current-window`**：表示当前窗口不再提示，当在新窗口访问时再提示
     - **新增 `cancelUpdateAndStopWorker` 选项**：取消更新后是否同时关闭 worker，默认 false
 
```
checkVersion(
  {
    ...
    pollingTime: 600000,
    immediate: true,
  },
  {
    ...
    cancelButtonText: 'Next time',
    cancelMode: 'ignore-today',
    cancelUpdateAndStopWorker: true,
  })
```
<img width="130" src="https://user-images.githubusercontent.com/26329117/213171634-7be6571b-2673-452d-89fb-795645773237.jpg" />

---

3. **提供自定义事件**

   - **`onRefresh()`**：确认更新时的自定义事件，返回最新版本号
   - **`onCancel()`**：取消更新时的自定义事件，返回最新版本号
 
```
checkVersion(
    {
      ...
      onRefresh: (data) => {
        console.log(data)   // {newVersion: 1.0.0}
      },
      onCancel: (data) => {
        console.log(data)   // {newVersion: 1.0.0}
      },
    })
```

**Comment by NWUFLAME** [comment]
LGTM   感谢！！！
