### ISSUE TITLE
`version-rocket`在`npm`中包大小的优化

### ISSUE THREAD

**Issue by xiaoxian521** [guMcrey/version-rocket#29]
很不错的一款工具，在使用过程中发现通过`npm`下载`version-rocket`后，包里貌似包含一些不必要的东西，比如下图的`assets`文件就占了`1.6MB`，可以在 [package-json的files](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#files) 字段设置只发布某些内容

<img width="687" alt="image" src="https://github.com/guMcrey/version-rocket/assets/44761321/4bfed332-15d0-4216-81bd-cce8c3556004">

**Comment by guMcrey** [comment]
好的，感谢反馈。我会尽快优化一下的，谢谢你的宝贵建议ᵔᴥᵔ

**Comment by guMcrey** [comment]
@xiaoxian521 你好呀, 我对 version-rocket 的 npm 包大小做了优化, 以下是优化后的包信息:

<img width="360" src="https://github.com/guMcrey/version-rocket/assets/26329117/ba20a810-e6de-4e0e-a844-425a7a7a4c92" />

--- 
如果在使用过程中有其他体验不好或者有问题的地方, 欢迎给我提 issue
再次感谢你的反馈ᵔᴥᵔ
