### ISSUE TITLE
希望增加页面激活时才触发轮询配置

### ISSUE THREAD

**Issue by Banana-energy** [guMcrey/version-rocket#43]
希望增加页面激活时才触发轮询

**Comment by guMcrey** [comment]
你好呀，请问是希望在访问特定路由时才触发监听对吗？

**Comment by Banana-energy** [comment]
不是，通过visibilitychange事件判断页面是否处于激活状态来减少不必要的轮询

**Comment by guMcrey** [comment]
明白了, 是个很好的想法. 通过监听 visibilitychange 事件来动态的开关 worker 能够有效的节省服务器资源、减少无意义的网络请求, 还可以节省用户的数据流量、延长设备的电池寿命。

```
document.addEventListener("visibilitychange", function() {
  if (document.visibilityState === "visible") {
      // 开始轮询
  } else {
      // 停止轮询
  }
});
```

关联 PR: https://github.com/guMcrey/version-rocket/pull/44

**Comment by Banana-energy** [comment]
是的，不确定是否需要配置来做这件事，个人理解默认使用这种模式即可

**Comment by guMcrey** [comment]
特别感谢你提出的建议。如果默认开启 `visibilitychange` 模式的想法确实简化了用户的配置工作，对于大多场景确实是一个很好的选择。不过，为了确保 version-rocket 在满足大多数用户需求的同时，也能提供必要的灵活性，以下是我对这个问题的一些思考：

**用户多样性：**

version-rocket 目前服务于广泛的用户群体，他们的使用场景和需求可能各不相同。虽然默认启用某个功能对绝大多数用户来说非常方便，但对另一些用户可能会产生意想不到的副作用。
例如，某些用户可能已经有自己的轮询逻辑，默认启用我们提供的轮询逻辑可能会导致冲突或性能问题。

**兼容性和过渡：**

对于已经在使用我们项目的现有用户，突然地启用新功能或默认行为，可能导致他们的系统出现兼容性问题或意外行为。
我希望在引入新功能时，能够确保平稳的过渡。因此，提供配置选项，让用户自己选择是否启用新功能，可以帮助他们更好地适应变化。

**灵活性和可扩展性：**

提供配置选项让用户能够根据自身需求决定是否启用某个功能，这种灵活性可以让项目更具适应性，满足更多样化的使用场景。
同时，给用户提供显式的方法去启用或禁用功能，也有助于提升项目的可扩展性和维护性。

所以, 我认为在初期阶段，我们可以保持通过配置选项来启用新功能的方法，确保向后兼容性和用户灵活性。在未来，我会根据用户反馈和项目发展，再视具体情况适时调整默认行为。

非常感谢你的贡献和支持~~💗

---

目前安装 `version-rocker@1.7.2` 已经修复了 worker 停止后未被初始化的问题, 有问题我们随时沟通
```
import { checkVersion, unCheckVersion } from 'version-rocket'
document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      checkVersion({
        originVersionFileUrl: `${location.origin}/version.json`,
        localPackageVersion: '1.1.0',
        immediate: true,
      })
    }
    else {
      unCheckVersion({ closeWorker: true })
    }
})
```
