### ISSUE TITLE
关于版本更新的疑问，求解答

### ISSUE THREAD

**Issue by masklong** [guMcrey/version-rocket#49]
### 开发环境：
1. umijs4框架搭建的后台项目

### 每次发包操作
1. 先build项目
2. 执行 generate:version
```
// package.json
"generate:version": "cross-env generate-version-file dist public",
```
3. 将 dist 文件部署到服务器

### 问题现象
版本比较失败，一直提示版本更新，点击版本更新后，下次轮询有会提示版本更新

**问题1:**
请问是因为我打包之前没有手动更改 package.json 里的version版本号导致的嘛？

但是我观察：每次执行 generate:version，会自动更新 version 版本号。

**问题2:**
实现原理是什么？“生产环境本质上是比较用户当前运行的 package.json 中的 version 与远程服务器中的 version.json 中的 version 是否一致”， 生产环境上是如何获取的package.json 中的 version？

**Comment by guMcrey** [comment]
你好呀, 很高兴回答你的问题

**一直提示版本更新的原因可能是:**
1. 浏览器缓存严重, 通过刷新页面无法更新缓存内容, 可以通过手动清除浏览器缓存后重试, 以 google 为例
<img src="https://github.com/user-attachments/assets/1290b9dc-68c4-441f-8c8c-533b0b608aa3" width="260" />

2. 其他, 如果通过 1 无法解决, 欢迎再与我联系

---

**问题2: 实现原理**
1. 当执行 `"generate:version": "generate-version-file dist public"` 时会获取项目根路径下的 package.json 文件生成 version.json 文件到 public 和 dist 目录下
2. 当部署 dist 目录到服务器之后, 会轮询向服务器发请求获取 version.json 文件
4. 然后与本地缓存的 version.json 文件内容做对比, 如果版本不同则提示更新; 版本相同则不提示

**问题1: 由实现原理得知**

每次执行 `generate:version` 并不会帮你自动更新版本号, 它只是拿到 package.json 的 version 字段生成 version.json 文件到 public 和 dist 目录下而已, 所以正确的操作步骤是:
1. 准备发布新版本前, 即 build 之前, 需要手动更新这次项目的版本号, 可以手动更新 package.json 文件或者执行[ `npm version 版本号` 来更新](https://docs.npmjs.com/cli/v10/commands/npm-version)
2. 打包项目
3. 然后执行 `generate:version` 就会将最新版本生成 version.json 文件 
> PS: 当然你可以将 2 3 合并, 将 generate:version 写到 build 指令中
4. 部署 dist 到目标服务器

**Comment by masklong** [comment]
感谢🙏
在build之前，手动更新版本号后，一切正常了
