### ISSUE TITLE
最新版`typescript`环境下报错

### ISSUE THREAD

**Issue by newives** [guMcrey/version-rocket#50]
<img width="1173" alt="图片" src="https://github.com/user-attachments/assets/3248d540-224e-4240-99a8-25b319b1f4e7">

报错信息如下：

node_modules/.pnpm/version-rocket@1.7.2/node_modules/version-rocket/index.ts:108:7 - error TS2872: This kind of expression is always truthy.

108       [...new Set(config.checkOriginSpecifiedFilesUrl)] || [],
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/version-rocket@1.7.2/node_modules/version-rocket/index.ts:108

**Comment by guMcrey** [comment]
你好呀, 我这边使用最新版 typescript, 安装 version-rocket@1.7.2, 从 node_modules 中查看 version-rocket/index.ts 文件 108 行没有报错
`"typescript": "^5.6.2"`

可以看下你的 package.json 和 tsconfig.json 配置吗?

**Comment by newives** [comment]
你好 我无法复现它 因为我的项目比较大 我试着新建个小项目复现但无法成功

下面我查到的语法错误原因，还希望作者可以看一下😝

<img width="926" alt="图片" src="https://github.com/user-attachments/assets/b8dd1501-7860-409d-a688-6dc6a8bd4a42">

[] || [] 确实会造成检测时的错误

**Comment by newives** [comment]
@guMcrey 可以解决一下吗 作者 着急上线😂

**Comment by guMcrey** [comment]
> @guMcrey 可以解决一下吗 作者 着急上线😂

好的

**Comment by guMcrey** [comment]
@newives 请安装 version-rocket@1.7.3, 看下是否还有 ts 错误

有问题的话, 再留言给我哦~

**Comment by newives** [comment]
牛 解决了 谢谢
