### ISSUE TITLE
Will the console have a warning?

### ISSUE THREAD

**Issue by wjp980108** [guMcrey/version-rocket#52]
Minimum reaping case

https://stackblitz.com/edit/vitejs-vite-qghqfs?file=src%2FApp.vue&terminal=dev

![image](https://github.com/user-attachments/assets/66e9dc02-4ffe-40f6-ac0f-abefa57ff6fd)

**Comment by guMcrey** [comment]
Hello, thank you for reporting this issue.
I have reproduced the issue and am currently working on a fix. I will update you once the issue has been resolved.

**Comment by guMcrey** [comment]
I have fixed the bug you reported in the latest commit. Please update to the latest version and let me know if you encounter any further issues.
`npm install version-rocket@1.7.4`

Thank you for helping improve the project!
