### ISSUE TITLE
generate-version-file 命令如何执行

### ISSUE THREAD

**Issue by changfun** [guMcrey/version-rocket#6]
你好，我是前端 generate-version-file 怎么执行啊，是Linux命令吗，不太懂

**Comment by guMcrey** [comment]
你好呀, generate-version-file 是 version-rocket 暴露出来的 shell 命令. generate-version-file 命令对应的文件会生成在当前安装目录的 ./node_modules/.bin/generate-version-file 下，你可以直接在命令行调用
```
node ./node_modules/.bin/generate-version-file
```

或者在项目中这样使用
1. 在package.json文件中的 scripts 命令中添加指令: `generate:version` , 值为 `generate-version-file`
_public dist 为希望生成的 version.json 所在的目录, 可以不传, 默认 dist_

```
{
  "name": "test",
  "description": "test",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    ...
    "generate:version": "generate-version-file public dist"
    ...
  },
  ...
}
```
3. 在控制台执行: `npm run generate:version` 即可 (此时你本地项目的 public 和 dist 目录下已生成了 version.json 文件)
_当然你可以在任何时机运行 `npm run generate:version`, 或者将 `generate-version-file` 放在 `build` scripts 命令中_

默认 version-rocket 会取本地项目的 package.json 文件的 version 字段与 public/version.json (dev 环境), dist/version.json (production 环境) 比较, 两者的 version 不同时, 展示版本提示弹窗

如果你有自定义 version 的需求, 也是支持的, 可以看下 README.zh-CN.md 文件的使用方法 https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md

希望对你有帮助, 感谢你的关注, 有任何问题欢迎题 issue 给我~
