### ISSUE TITLE
可以在企业微信里面发通知吗？

### ISSUE THREAD

**Issue by lvwapro** [guMcrey/version-rocket#8]

**Comment by guMcrey** [comment]
感谢关注，目前还不支持企业微信，我先去调研一下，能支持的话，尽快同步给你哦(๑˙ー˙๑)

**Comment by guMcrey** [comment]
你好, 安装 v1.3.0 最新版就可以发送部署消息到企业微信了, 具体使用方法请参考文档 [支持推送部署成功的通知到 企业微信(WeCom) 群聊](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#%E6%94%AF%E6%8C%81%E6%8E%A8%E9%80%81%E9%83%A8%E7%BD%B2%E6%88%90%E5%8A%9F%E7%9A%84%E9%80%9A%E7%9F%A5%E5%88%B0-%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1wecom-%E7%BE%A4%E8%81%8A)

感谢反馈, 如有其他疑问欢迎提 issue 给我❤️

**Comment by lvwapro** [comment]
请教一下哈，这部分写入到哪个文件里面？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guMcrey/version-rocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guMcrey/version-rocket] 可以在企业微信里面发通知吗？ (Issue #8)





 
你好, 安装 v1.3.0 最新版就可以发送部署消息到企业微信了, 具体使用方法请参考文档 支持推送部署成功的通知到 企业微信(WeCom) 群聊
 
感谢反馈, 如有其他疑问欢迎提 issue 给我❤️

**Comment by guMcrey** [comment]
@HelloWorldya 
使用方法：
1. 在项目本地新建 message-config.json 文件， 文件字段和内容参考如下
```javascript

{
    // 消息卡片标题
    "title": "TEST FE Deployed Successfully",
    // 可选: 项目名称标签, 默认 Project Name
    "projectNameLabel": "Project name label",
    // 项目名称
    "projectName": "TEST",
    // 可选: 项目分支标签, 默认 Branch
    "branchLabel": "Branch label",
    // 项目分支, 可用于区别部署环境
    "branch": "Staging",
    // 可选: 版本标签, 默认 Version
    "versionLabel": "Version label",
    // 版本
    "version": "1.1.1.0",
    // 可选: 项目可访问地址标签, 默认 URL
    "accessUrlLabel": "Access URL label",
    // 项目可访问地址
    "accessUrl": "https://test.com",
    // 是否@所有人: true / false
    "isNotifyAll": true,
    // 企业微信机器人的 webhook 链接
    "webHook": "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxx",
    // 可选: 部署工具描述
    "deployToolsText": "Deploy tools text",
    // 可选: 部署时间想要转换成的时区，默认 "Asia/Shanghai" (当你的项目要部署的目标服务器与你所在时区不同, 可以设置此字段来转换时区)
    "expectConvertToTimezone": "America/New_York"
    // 可选: 想要展示除模版之外的更多信息
    "remark": "Trigger by bob, fix xxx bug"
}

```

2. 在 package.json 文件 scripts 中新建自定义执行命令 `send-wecom-message:test`
```javascript

// package.json

{
  "name": "test",
   ...
  "scripts": 
    "send-wecom-message:test": "send-wecom-message"
    ...
  },
  ...
}

```

3. 控制台执行 npm run send-wecom-message:test 即可，企业微信消息就发送成功了

更多详情参见[文档](https://github.com/guMcrey/version-rocket/blob/main/README.zh-CN.md#%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1-wecom)，感谢关注
